const menus= [{
    title:'Menu 1',
    soup: 'Minestrone',
    soupPrice: '$2.95',
    salad:'Greek Salad',
    saladPrice: '$4.75',
    lighterFare: 'Vegetable Biriyanin ',
    lighterFarePrice: '$4.95',
    entree: 'Breaded Chicken  on a Bun',
    entreePrice: '$5.95',
    },{
    title:'Menu 2',
    soup: 'Red Lentil Dal',
    soupPrice: '$2.95',
    salad:'Julienne Salad',
    lighterFare: 'Madras Chicken Salad Wrap',
    lighterFarePrice: '$4.95',
    entree: 'Fish$Chips',
    entreePrice: '$5.95',
    },{
    title:'Menu 3',
    soup: 'Spicy Squash & Pumpkin',
    soupPrice: '$2.95',
    salad:'Mediterranean Salad',
    lighterFare: 'Ham & Cheese Panini',
    lighterFarePrice: '$4.95',
    entree: 'BNutter Chicken with Race ',
    entreePrice: '$5.95',
    },{
    title:'Menu 4',
    soup: 'Calm Chowder',
    soupPrice: '$2.95',
    salad:'Israeli =Salad',
    lighterFare: 'Pulled Porke on a Bun',
    lighterFarePrice: '$4.95',
    entree: 'Matar Panner $ Basmati',
    entreePrice: '$5.95',
    },{
    title:'Menu 5',
    soup: 'Tomato',
    soupPrice: '$2.95',
    salad:'Caesar Salad',
    lighterFare: 'Burger & Fries',
    lighterFarePrice: '$4.95',
    entree: 'Beef & Broccoli with rice',
    entreePrice: '$5.95',
    }];